AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'lab/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
